import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Air Jordan 1 Retro High OG",
    brand: "Nike / Jordan",
    category: "Men",
    condition: "New",
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["Chicago", "Bred"],
    price: 185000,
    deliveryFee: 5000,
    images: ["https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=1000"],
    vendorId: "v1",
    vendorLocation: "Lagos",
    description: "The classic Chicago colorway. A must-have for every collection.",
    status: "active",
    isInstallmentEligible: true,
    createdAt: Date.now(),
  },
  {
    id: "2",
    name: "Yeezy Boost 350 V2 'Carbon'",
    brand: "Adidas / Yeezy",
    category: "Men",
    condition: "Fairly Used",
    sizes: ["42", "43"],
    colors: ["Black/Grey"],
    price: 95000,
    deliveryFee: 4000,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1000"],
    vendorId: "v2",
    vendorLocation: "Abuja",
    description: "Clean condition, 9/10. Box included.",
    status: "active",
    isInstallmentEligible: true,
    createdAt: Date.now(),
  },
  {
    id: "3",
    name: "Classic Leather Loafers",
    brand: "Gucci",
    category: "Loafers",
    condition: "New",
    sizes: ["41", "42", "43", "44", "45"],
    colors: ["Black", "Brown"],
    price: 320000,
    deliveryFee: 8000,
    images: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=1000"],
    vendorId: "v1",
    vendorLocation: "Lagos",
    description: "Italian leather, premium finish. Perfect for corporate and luxury settings.",
    status: "active",
    isInstallmentEligible: false,
    createdAt: Date.now(),
  },
  {
    id: "4",
    name: "Classic Clog 'Black'",
    brand: "Crocs",
    category: "Crocs",
    condition: "New",
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    colors: ["Black"],
    price: 45000,
    deliveryFee: 3000,
    images: ["https://images.unsplash.com/photo-1626947346165-4c2288dadc2a?auto=format&fit=crop&q=80&w=1000"],
    vendorId: "v3",
    vendorLocation: "Port Harcourt",
    description: "Original Crocs for everyday comfort.",
    status: "active",
    isInstallmentEligible: false,
    createdAt: Date.now(),
  },
  {
    id: "5",
    name: "Classic Leather Pumps",
    brand: "Prada",
    category: "Women",
    condition: "New",
    sizes: ["36", "37", "38", "39"],
    colors: ["Beige"],
    price: 450000,
    deliveryFee: 10000,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=1000"],
    vendorId: "v4",
    vendorLocation: "Lagos",
    description: "Elegant Prada pumps, brand new. Perfect for formal events.",
    status: "active",
    isInstallmentEligible: true,
    createdAt: Date.now(),
  }
];

export const CATEGORIES = [
  "Men",
  "Women",
  "Slides",
  "Crocs",
  "Loafers",
  "Corporate shoes",
  "Boots",
  "Sandals"
];

export const LOCATIONS = [
  "Lagos",
  "Abuja",
  "Port Harcourt",
  "Warri",
  "Delta",
  "Kano",
  "Enugu"
];

export const MOCK_WALLET_RECORDS = [
  {
    id: "w1",
    userId: "u1",
    orderId: "o1",
    transactionType: "Full Payment",
    amount: 190000,
    description: "Nike Air Jordan 1 Retro",
    status: "Successful",
    balanceType: "payment",
    createdAt: Date.now() - 86400000,
  },
  {
    id: "w2",
    userId: "u1",
    orderId: "o2",
    transactionType: "Part Payment",
    amount: 45000,
    description: "Yeezy Boost 350 - 1st Installment",
    status: "Successful",
    balanceType: "payment",
    createdAt: Date.now() - 432000000,
  }
];

export const MOCK_INSTALLMENTS = [
  {
    id: "i1",
    userId: "u1",
    orderId: "o2",
    productName: "Yeezy Boost 350 V2",
    totalAmount: 99000,
    amountPaid: 45000,
    balanceRemaining: 54000,
    nextDueDate: Date.now() + 604800000,
    status: "active",
  }
];
